Projeto Final - Mídulo 1 - SCTEC

#Fase 4: Divisão e Balanceamento dos Dados

Separe as variáveis preditoras (X) da variável alvo (y).
Divida os dados em treino (80%) e teste (20%) utilizando o parâmetro stratify=y.
Aplique uma técnica de reamostragem (SMOTE ou Random Under Sampling) exclusivamente nos dados de treino para evitar o vazamento de dados (Data Leakage).

In [1]:
# Configuração inicial para todos os notebooks

# Importação das bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Configuração do visual global
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams["figure.figsize"] = (12, 6)
plt.rcParams["axes.titlesize"] = 14
plt.rcParams["axes.labelsize"] = 12

print("n\=== CONFIGURAÇÕES E BIBLIOTECAS IMPORTADAS COM SUCESSO ===")

<>:16: SyntaxWarning: "\=" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\="? A raw string is also an option.
<>:16: SyntaxWarning: "\=" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\="? A raw string is also an option.
C:\Users\User\AppData\Local\Temp\ipykernel_12684\217933160.py:16: SyntaxWarning: "\=" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\="? A raw string is also an option.
  print("n\=== CONFIGURAÇÕES E BIBLIOTECAS IMPORTADAS COM SUCESSO ===")

n\=== CONFIGURAÇÕES E BIBLIOTECAS IMPORTADAS COM SUCESSO ===

In [5]:
# Carregando os dados do dataset de engenharia

df_fe = pd.read_csv("../data/processed/manutencao_preditiva_fe.csv", sep=",")
df_fe.head()

,id_produto,tipo,temperatura_ar_k,temperatura_processo_k,velocidade_rotacao_rpm,torque_nm,desgaste_ferramenta_min,falha_maquina,potencia_calc
0,M14860,M,298.1,308.6,1551.0,42.8,0,0,66382.8
1,L47181,L,298.2,308.7,1408.0,46.3,3,0,65190.4
2,L47182,L,298.1,308.5,1498.0,49.4,5,0,74001.2
3,L47183,L,300.1,310.1,1504.0,40.1,7,0,60310.4
4,L47184,L,298.2,308.7,1408.0,40.0,9,0,56320.0

In [ ]:
# Separando as variáveis preditoras (x) eliminando a coluna da variável alvo (falha_maquina)

X = df_fe.drop(columns=["falha_maquina"]) # X é maiúsculo
X.head()

,id_produto,tipo,temperatura_ar_k,temperatura_processo_k,velocidade_rotacao_rpm,torque_nm,desgaste_ferramenta_min,potencia_calc
0,M14860,M,298.1,308.6,1551.0,42.8,0,66382.8
1,L47181,L,298.2,308.7,1408.0,46.3,3,65190.4
2,L47182,L,298.1,308.5,1498.0,49.4,5,74001.2
3,L47183,L,300.1,310.1,1504.0,40.1,7,60310.4
4,L47184,L,298.2,308.7,1408.0,40.0,9,56320.0

In [13]:
# Isolando apenas a variável alvo

y = df_fe["falha_maquina"] # y é minúsculo
y.head()

0    0
1    0
2    0
3    0
4    0
Name: falha_maquina, dtype: int64

In [ ]:
# Dividindo a base de dados em treino (80%) e teste (20%)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, stratify=y, random_state=42
)
print(f"Dimensões de treino (X_train): {X_train.shape}") # (quantidade de linhas, colunas)
print(f"Dimensões de teste (X_test): {X_test.shape}")

Dimensões de treino (X_train): (8000, 8)
Dimensões de teste (X_test): (2000, 8)

from sklearn.utils import resample

# 4. Balanceamento de classes via técnica de reamostragem (Random Under Sampling)
treino_completo = pd.concat([X_train, y_train], axis=1)
classe_normal = treino_completo[treino_completo['falha_maquina'] == 0]
classe_falha = treino_completo[treino_completo['falha_maquina'] == 1]

# Reduzindo a classe majoritária para o tamanho da minoritária
classe_normal_subamostrada = resample(
    classe_normal, replace=False, n_samples=len(classe_falha), random_state=42
)

treino_balancedo = pd.concat([classe_normal_subamostrada, classe_falha])
X_train_bal = treino_balancedo.drop(columns=['falha_maquina'])
y_train_bal = treino_balancedo['falha_maquina']

In [ ]:
# Balanceamento de classes por reamostragem (Random Under Sampling)

# importando a ferramente resample
from sklearn.utils import resample

treino_completo = pd.concat([X_train, y_train], axis=1)
classe_normal = treino_completo[treino_completo['falha_maquina'] == 0]
classe_falha = treino_completo[treino_completo['falha_maquina'] == 1]

# Reduzindo a classe majoritária para o tamanho da minoritária
classe_normal_subamostrada = resample(
    classe_normal, replace=False, n_samples=len(classe_falha), random_state=42
) 

treino_balanceado = pd.concat([classe_normal_subamostrada, classe_falha])
X_train_bal = treino_balanceado.drop(columns=['falha_maquina'])
y_train_bal = treino_balanceado['falha_maquina']

y_train_bal.value_counts() # mostra a quantidade de linhas de cada uma (0 e 1). Devem ser iguais.

falha_maquina
0    271
1    271
Name: count, dtype: int64